# RANDOM MODULE FUNCTION:

In [ ]:
In NumPy, the random module is used to generate random numbers, random arrays, and perform random operations.
It is very useful in data analytics, simulations, machine learning, and testing.

In [1]:
import numpy as np

In [2]:
np.random

<module 'numpy.random' from 'C:\\Users\\si310\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\random\\__init__.py'>

In [ ]:
# 1. rand()

Generates random numbers between 0 and 1.

In [3]:
np.random.rand(rowS, columns)

NameError: name 'rows' is not defined

In [4]:
import numpy as np

a = np.random.rand(2,3)
print(a)

[[0.43442781 0.3555879  0.58965532]
 [0.52976921 0.85209355 0.37705015]]


In [ ]:
# 2. randn()

Generates random numbers from a normal distribution.

Mean = 0
Standard deviation = 1

In [ ]:
np.random.randn(rows, columns)

In [5]:
a = np.random.randn(2,2)
print(a)

[[ 1.56806421 -2.20260465]
 [-0.14549246 -0.47712767]]


# 1. randint()

In [ ]:
Generates random integers between a range.

In [ ]:
np.random.randint(start, end, size)

In [6]:
a = np.random.randint(1, 10, 5)
print(a)

[6 9 3 4 6]


# 2. random()

In [ ]:
Generates random float numbers between 0 and 1.

In [ ]:
np.random.random(size)

In [7]:
a = np.random.random((2,2))
print(a)

[[0.72150568 0.86439529]
 [0.55600166 0.38821698]]


# 3. seed()

In [ ]:
Used to generate the same random numbers every time.

In [8]:
np.random.seed(1)

print(np.random.randint(1,10,5))

[6 9 6 1 1]


# 4. shuffle()

In [ ]:
Shuffles original array.

In [10]:
a = np.array([1,2,3,4,5])

np.random.shuffle(a)

print(a)

[5 4 1 3 2]


# 5. choice()

In [ ]:
Selects random values from array.

In [11]:
a = np.random.choice([10,20,30,40], 3)

print(a)

[20 30 10]


In [ ]:
# Simple Practice Program

import numpy as np

# Random integers
a = np.random.randint(1,100,10)

print("Random Numbers:")
print(a)

# Shuffle
np.random.shuffle(a)

print("After Shuffle:")
print(a)

In [ ]:
#Summary Table
  Function	                             Purpose
rand()	                      Random floats between 0 and 1
randn()	                      Random values from normal distribution
randint()	                  Random integers
random()	                  Random float array
seed()	                      Repeat same random values
shuffle()	                  Shuffle original array
permutation()	              Shuffled copy
uniform()	                  Random numbers in range
normal()	                  Normal distribution values
choice()	                  Random selection